version: '3.1'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - 5678:5678
    environment:
      - DB_TYPE=sqlite
      - DB_SQLITE_PATH=/data/database.sqlite
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - NODE_OPTIONS=--max-old-space-size=512
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./n8n_data:/data